### ISSUE TITLE
Scenes Missing

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc/UD-Mobile-iOS#17] opened 2021-03-22 20:30 UTC
In Devices and Scenes, I’m not seeing any scenes only devices in some rooms.  I have ISY organized by rooms and  some of my rooms does not include scenes.

**Comment by hart-2-hart** [comment] 2021-03-22 20:33
Correction.  I have them organized by rooms and one of my larger rooms device count wise does not include scenes.

**Comment by JavierRefuerzo** [comment] 2021-03-22 20:37
Hi @hart-2-hart ,
Please clerify your second post. I don't quite understand if the issue is resolved.

If missing please check if the missing scenes are group="4", if they are this will be fixed in the next update. It was a bug in both Android and iOS
https://forum.universal-devices.com/topic/32218-missing-scenes/?do=findComment&comment=309071

**Comment by hart-2-hart** [comment] 2021-03-22 20:39
Hi.  That is the same issue.  I searched GitHub looking for duplicates.  I
now understand to look at forum.  Sorry about that.

Paul

**Comment by JavierRefuerzo** [comment] 2021-03-22 20:54
Hi Paul,

No worries, it was not reported here. I was just trying to avoid typing an explanation with the link.

Closing as group="4" bug will be fixed in the next release

**Closed by JavierRefuerzo** 2021-03-22 20:54 UTC
