### ISSUE TITLE
Error with nodeserver 10- Harmony Hub (Pg3)

### ISSUE THREAD

**Issue by macjeff** [UniversalDevicesInc/UD-Mobile-iOS#54] opened 2022-02-23 02:31 UTC
I updated to IoP and just finished.  I deleted everything from your app and started new.

Good news- only 1 error and the one from last week is gone (per the new update)

See error in screenshot.  THANKS!!
![IMG_6909](https://user-images.githubusercontent.com/20373758/155252654-272c67d8-e35a-4313-b13b-acfd70b829f5.jpeg)

**Comment by JavierRefuerzo** [comment] 2022-02-24 17:16
Hi Jeff,  

iOS version 0.6.8 went live this morning. Issue should be corrected.
Duplicate of #51

**Closed by JavierRefuerzo** 2022-02-24 17:16 UTC
