### ISSUE TITLE
Empty Editor should not show as ERROR

### ISSUE THREAD

**Issue by macjeff** [UniversalDevicesInc/UD-Mobile-iOS#51] opened 2022-02-18 01:10 UTC
I installed Pg3 and updated most nodeservers but still a few not ready for Pg3 so also running Pg2.

I just did my first sync on UD Mobile since then.  Attached is screenshot of error code.  I have no network resources so that error is normal but its the first one.

thanks,

Jef
![Screenshot 2022-02-17 at 8 02 14 PM](https://user-images.githubusercontent.com/20373758/154598265-559d9fc2-abb2-46bf-804e-5cd33e83e382.png)
f

**Comment by JavierRefuerzo** [comment] 2022-02-18 01:44
Hi Jeff,

Number 2 can be ignored.

Number 1:
What Node Server is installed in slot 11?
Is the same error presented every time synchronization occurs?

**Comment by macjeff** [comment] 2022-02-18 16:24
also emailed the developer of the nodeserver to check on adding editor file

**Comment by JavierRefuerzo** [comment] 2022-02-18 16:35
If using chrome and on the local network, the browser will prompt for credentials so no need to add them in the url.  The url posted also has two forward slashes before "rest". Assuming this is on Polisy the default port is 8080.  If this is remote and you have ISY portal replace <ipaddres>:8080 with URL to ISY.
http://<ipaddress>:8080/rest/profiles/family/10/files

**Comment by macjeff** [comment] 2022-02-18 16:50
Now I get a login and then the UD logo in the FavIcon so I know I am there.
but page is blank

**Comment by JavierRefuerzo** [comment] 2022-02-18 16:54
sorry I just noticed that part of my url was removed due to formatting should be something like this
http://192.168.1.160:8080/rest/profiles/family/10/files
what url are you using.

**Comment by macjeff** [comment] 2022-02-18 17:29
<profiles>
<profile family="10" id="1">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
<files dir="EDITOR">
<file name="I_EDIT.XML"/>
</files>
<files dir="NODEDEF">
<file name="I_NDEFS.XML"/>
</files>
</profile>
<profile family="10" id="2">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
</profile>
<profile family="10" id="3">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="4">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
<file name="CUSTOM.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
<file name="CUSTOM.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="5">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="6">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="7">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="8">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="9">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="10">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
<file name="CUSTOM.XML"/>
</files>
<files dir="EDITOR">
<file name="CUSTOM.XML"/>
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="11">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="12">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="13">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="14">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="15">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
<file name="ISYHOME.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
<file name="CUSTOM.XML"/>
<file name="ISYHOME.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="16">
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="17">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="18">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="19">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="20">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="21">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="22">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
</profile>
<profile family="10" id="23">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
</profiles>

**Comment by macjeff** [comment] 2022-02-18 17:33
<profiles>
<profile family="10" id="1">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
<files dir="EDITOR">
<file name="I_EDIT.XML"/>
</files>
<files dir="NODEDEF">
<file name="I_NDEFS.XML"/>
</files>
</profile>
<profile family="10" id="2">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
</profile>
<profile family="10" id="3">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="4">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
<file name="CUSTOM.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
<file name="CUSTOM.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="5">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="6">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="7">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="8">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="9">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="10">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
<file name="CUSTOM.XML"/>
</files>
<files dir="EDITOR">
<file name="CUSTOM.XML"/>
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="11">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="12">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="13">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="14">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="15">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
<file name="ISYHOME.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
<file name="CUSTOM.XML"/>
<file name="ISYHOME.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="16">
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="17">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="18">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="19">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="20">
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="21">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
<profile family="10" id="22">
<files dir="NODEDEF">
<file name="NODEDEF.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
</profile>
<profile family="10" id="23">
<files dir="NODEDEF">
<file name="NODEDEFS.XML"/>
</files>
<files dir="EDITOR">
<file name="EDITORS.XML"/>
</files>
<files dir="NLS">
<file name="EN_US.TXT"/>
</files>
</profile>
</profiles>

**Comment by macjeff** [comment] 2022-02-18 17:34
can you ready what I just sent.  I cant see it on my end   just in case I uploaded a txt file
[output.txt](https://github.com/UniversalDevicesInc/UD-Mobile-iOS/files/8099249/output.txt)
.

**Comment by JavierRefuerzo** [comment] 2022-02-18 17:42
Great. Looks like it has and editor. Please request the editor file and post here.  The code button at the top of comments will allow it to be formatted correctly if pasted between the "`" symbols

http://192.168.1.160:8080/rest/profiles/family/10/profile/11/download/EDITOR/EDITORS.XML

**Comment by JavierRefuerzo** [comment] 2022-02-18 18:24
Perfect, you have isolated the issue.  I opened and issue with the developer below. Thanks for you assistance!
https://github.com/simplextech/pg3_docs/issues/2

**Comment by JavierRefuerzo** [comment] 2022-02-18 20:02
Jeff,
Looks like the formatting was missed in your reply, I have edited it to show the correct values.

Is the node server working as intended?   The Node server dev says it is empty, so this may fall under the possible errors category.

**Comment by JavierRefuerzo** [comment] 2022-02-18 23:41
Great.  Empty Editor will be changed to a possible error.

**Comment by JavierRefuerzo** [comment] 2022-02-21 16:13
Fixed in version 0.6.8

**Closed by JavierRefuerzo** 2022-02-21 16:13 UTC
