### ISSUE TITLE
Error Adding/Editing Configure Color/Values/Icons for Z-Wave Device

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#47] opened 2021-12-19 17:50 UTC
I get the following error when adding or editing a Configure Color/Values/Icons entry for a Z-Wave device.

"Editor Object does not have an ID"

I don't get this error with Insteon devices or Node Servers.  Once you acknowledge the error message, you can still add or edit an entry and save and they function properly.

**Comment by JavierRefuerzo** [comment] 2021-12-19 18:34
Hi @mbking1 ,

I think this issue was corrected in the latest version, but may require synchronization.  Does the issue persist after upgrade and synchronization?  

Dev Notes: Possible duplicate of Android issue, should have been corrected for iOS in version 0.6.0 https://github.com/UniversalDevicesInc/UD-Mobile-Android/issues/27

**Comment by mbking1** [comment] 2021-12-19 20:42
My bad.  I re-sync'd with 5.9, not 6.0.  Problem solved.  Sorry for the false alarm.  

Mark

**Comment by mbking1** [comment] 2021-12-19 20:43
Problem solved, issue closed

**Closed** 2021-12-19 20:43 UTC
