### ISSUE TITLE
Ordering a button among data elements

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc/UD-Mobile-iOS#39] opened 2021-05-19 01:46 UTC
When attempting to reorder components of a node, moving a button up among pure data elements will either crash the app or the change will not stick.  Using Venstar NodeLink thermostat.

**Comment by JavierRefuerzo** [comment] 2021-05-19 13:33
Hi @hart-2-hart ,

Version 0.2.7 should be released sometime today, this fixes a crash when an element is moved to an invalid section.  Please let me know if the issue is not resolved in 0.2.7. and I'll try to fix before 0.2.8 is submitted for review.

Version 0.2.8 will have visual queues alerting the user that an element can not be moved to another section.  Status elements and button elements can only be sequenced within their respective sections.

Thanks

**Comment by hart-2-hart** [comment] 2021-05-19 15:22
It no longer allows button to move into information section and the crash
does not occur.

**Comment by JavierRefuerzo** [comment] 2021-05-19 15:34
Great, Thank you for the quick verification.

**Closed by JavierRefuerzo** 2021-05-19 15:34 UTC
